services:
  postgres:
    image: postgres:16-alpine
    container_name: kolbak-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: metadata-db
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kolbak-network

  redis:
    image: redis:7-alpine
    container_name: kolbak-redis
    command: redis-server --requirepass redis123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis123", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kolbak-network

networks:
  kolbak-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: